rule = [
  {
    matches = [
      { "api.bluez5.address" = "64:68:76:71:7A:C5" }
    ]
    actions = {
      update-properties = {
        "bluez5.codec" = "ldac"
        "bluez5.ldac.quality" = "hq"
        "bluez5.rate" = 96000
        "bluez5.bitrate" = 990000
      }
    }
  }
]
